### ISSUE TITLE
Is ruby a dependency?

### ISSUE THREAD

**Issue by autra** [gasolin/foxbox#43]
My system complains when running `./configure.sh`, with the following logs.

Is ruby a dependency, and if yes, which version should I use?

```
███████╗ ██████╗ ██╗  ██╗██████╗  ██████╗ ██╗  ██╗
██╔════╝██╔═══██╗╚██╗██╔╝██╔══██╗██╔═══██╗╚██╗██╔╝
█████╗  ██║   ██║ ╚███╔╝ ██████╔╝██║   ██║ ╚███╔╝ 
██╔══╝  ██║   ██║ ██╔██╗ ██╔══██╗██║   ██║ ██╔██╗ 
██║     ╚██████╔╝██╔╝ ██╗██████╔╝╚██████╔╝██╔╝ ██╗
╚═╝      ╚═════╝ ╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚═╝  ╚═╝
      FirefoxOS Build Environment in a VM         
OS: linux
DIST: Ubuntu
REV: 15.04
DistroBasedOn: debian
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dkms is already the newest version.
nfs-common is already the newest version.
nfs-kernel-server is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded.
start vagrant with /home/augustin/workspace/mozilla/gaia/foxbox/gaia
/home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/common.rb:67: [BUG] Segmentation fault at 0x00000000000018
ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]

-- Control frame information -----------------------------------------------
c:0018 p:---- s:0072 e:000071 CFUNC  :initialize
c:0017 p:---- s:0070 e:000069 CFUNC  :new
c:0016 p:0075 s:0067 e:000064 METHOD /home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/common.rb:67
c:0015 p:0070 s:0056 e:000054 CLASS  /home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/ext.rb:17
c:0014 p:0011 s:0053 e:000052 CLASS  /home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/ext.rb:12
c:0013 p:0057 s:0051 e:000050 TOP    /home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/ext.rb:9 [FINISH]
c:0012 p:---- s:0049 e:000048 CFUNC  :require
c:0011 p:0115 s:0045 e:000044 METHOD /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55
c:0010 p:0019 s:0035 e:000034 CLASS  /home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json.rb:58
c:0009 p:0017 s:0033 e:000032 TOP    /home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json.rb:54 [FINISH]
c:0008 p:---- s:0031 e:000030 CFUNC  :require
c:0007 p:0115 s:0027 e:000026 METHOD /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55
c:0006 p:0007 s:0017 e:000016 TOP    /usr/lib/ruby/vendor_ruby/vagrant/plugin/state_file.rb:1 [FINISH]
c:0005 p:---- s:0015 e:000014 CFUNC  :require_relative
c:0004 p:0039 s:0011 e:000010 TOP    /usr/lib/ruby/vendor_ruby/vagrant/plugin/manager.rb:6 [FINISH]
c:0003 p:---- s:0009 e:000008 CFUNC  :require_relative
c:0002 p:0117 s:0005 E:000dc0 EVAL   /usr/lib/ruby/vendor_ruby/vagrant/pre-rubygems.rb:20 [FINISH]
c:0001 p:0000 s:0002 E:000968 TOP    [FINISH]

-- Ruby level backtrace information ----------------------------------------
/usr/lib/ruby/vendor_ruby/vagrant/pre-rubygems.rb:20:in `<main>'
/usr/lib/ruby/vendor_ruby/vagrant/pre-rubygems.rb:20:in `require_relative'
/usr/lib/ruby/vendor_ruby/vagrant/plugin/manager.rb:6:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/vagrant/plugin/manager.rb:6:in `require_relative'
/usr/lib/ruby/vendor_ruby/vagrant/plugin/state_file.rb:1:in `<top (required)>'
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json.rb:54:in `<top (required)>'
/home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json.rb:58:in `<module:JSON>'
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/ext.rb:9:in `<top (required)>'
/home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/ext.rb:12:in `<module:JSON>'
/home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/ext.rb:17:in `<module:Ext>'
/home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/common.rb:67:in `generator='
/home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/common.rb:67:in `new'
/home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/common.rb:67:in `initialize'

-- C level backtrace information -------------------------------------------
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x18a4b7) [0x7f53937a04b7]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x18a583) [0x7f53937a0583]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x6db13) [0x7f5393683b13] printf-parse.h:88
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(rb_bug+0xb3) [0x7f5393684183] printf-parse.h:75
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x12090e) [0x7f539373690e] getnetgrent_r.c:486
/lib/x86_64-linux-gnu/libc.so.6(+0x352f0) [0x7f53932812f0] ../sysdeps/posix/killpg.c:37
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(rb_hash_aref+0xc) [0x7f53936a354c] ../sysdeps/x86_64/strrchr.S:128
/home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/ext/generator.so(+0x2c32) [0x7f53904f8c32] generator.c:555
/home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/ext/generator.so(+0x320a) [0x7f53904f920a] generator.c:982
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x1753a6) [0x7f539378b3a6]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x176957) [0x7f539378c957]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(rb_class_new_instance+0x21) [0x7f53936d52a1] strptime_l.c:416
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x174626) [0x7f539378a626]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x1802dd) [0x7f53937962dd]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x179593) [0x7f539378f593]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x17f0ab) [0x7f53937950ab]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(rb_iseq_eval+0x129) [0x7f5393797ae9]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x754b0) [0x7f539368b4b0] wfileops.c:937
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(rb_require_safe+0x694) [0x7f539368cce4] clearerr.c:27
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x174626) [0x7f539378a626]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x179593) [0x7f539378f593]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x17f0ab) [0x7f53937950ab]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(rb_iseq_eval+0x129) [0x7f5393797ae9]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x754b0) [0x7f539368b4b0] wfileops.c:937
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(rb_require_safe+0x694) [0x7f539368cce4] clearerr.c:27
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x174626) [0x7f539378a626]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x179593) [0x7f539378f593]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x17f0ab) [0x7f53937950ab]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(rb_iseq_eval+0x129) [0x7f5393797ae9]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x754b0) [0x7f539368b4b0] wfileops.c:937
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(rb_require_safe+0x694) [0x7f539368cce4] clearerr.c:27
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x174626) [0x7f539378a626]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x1802dd) [0x7f53937962dd]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x179593) [0x7f539378f593]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x17f0ab) [0x7f53937950ab]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(rb_iseq_eval+0x129) [0x7f5393797ae9]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x754b0) [0x7f539368b4b0] wfileops.c:937
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(rb_require_safe+0x694) [0x7f539368cce4] clearerr.c:27
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x174626) [0x7f539378a626]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x1802dd) [0x7f53937962dd]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x179593) [0x7f539378f593]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x17f0ab) [0x7f53937950ab]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(rb_iseq_eval_main+0x7f) [0x7f5393797b9f]
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(+0x711bb) [0x7f53936871bb] libioP.h:892
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(ruby_exec_node+0x1d) [0x7f5393688add] fwscanf.c:27
/usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1(ruby_run_node+0x1e) [0x7f539368a39e] wgenops.c:735
/usr/bin/ruby2.1() [0x40086b]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f539326ca40] libc-start.c:289
/usr/bin/ruby2.1() [0x400899]

-- Other runtime information -----------------------------------------------

* Loaded script: /usr/lib/ruby/vendor_ruby/vagrant/pre-rubygems.rb

* Loaded features:

    0 enumerator.so
    1 /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/encdb.so
    2 /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/trans/transdb.so
    3 /usr/lib/x86_64-linux-gnu/ruby/2.1.0/rbconfig.rb
    4 /usr/lib/ruby/2.1.0/rubygems/compatibility.rb
    5 /usr/lib/ruby/2.1.0/rubygems/defaults.rb
    6 /usr/lib/ruby/2.1.0/rubygems/deprecate.rb
    7 /usr/lib/ruby/2.1.0/rubygems/errors.rb
    8 /usr/lib/ruby/2.1.0/rubygems/version.rb
    9 /usr/lib/ruby/2.1.0/rubygems/requirement.rb
   10 /usr/lib/ruby/2.1.0/rubygems/platform.rb
   11 /usr/lib/ruby/2.1.0/rubygems/basic_specification.rb
   12 /usr/lib/ruby/2.1.0/rubygems/stub_specification.rb
   13 /usr/lib/ruby/2.1.0/rubygems/util/stringio.rb
   14 /usr/lib/ruby/2.1.0/rubygems/specification.rb
   15 /usr/lib/ruby/2.1.0/rubygems/exceptions.rb
   16 /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb
   17 /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb
   18 thread.rb
   19 /usr/lib/x86_64-linux-gnu/ruby/2.1.0/thread.so
   20 /usr/lib/ruby/2.1.0/monitor.rb
   21 /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb
   22 /usr/lib/ruby/2.1.0/rubygems.rb
   23 /usr/lib/x86_64-linux-gnu/ruby/2.1.0/pathname.so
   24 /usr/lib/ruby/2.1.0/pathname.rb
   25 /usr/lib/ruby/2.1.0/delegate.rb
   26 /usr/lib/x86_64-linux-gnu/ruby/2.1.0/etc.so
   27 /usr/lib/ruby/2.1.0/fileutils.rb
   28 /usr/lib/ruby/2.1.0/tmpdir.rb
   29 /usr/lib/ruby/2.1.0/tempfile.rb
   30 /usr/lib/ruby/vendor_ruby/vagrant/shared_helpers.rb
   31 /usr/lib/ruby/2.1.0/set.rb
   32 /usr/lib/ruby/vendor_ruby/bundler/gem_path_manipulation.rb
   33 /usr/lib/ruby/vendor_ruby/bundler/gem_helpers.rb
   34 /usr/lib/ruby/vendor_ruby/bundler/match_platform.rb
   35 /usr/lib/ruby/2.1.0/rubygems/dependency.rb
   36 /usr/lib/ruby/vendor_ruby/bundler/rubygems_ext.rb
   37 /usr/lib/ruby/2.1.0/rubygems/path_support.rb
   38 /usr/lib/x86_64-linux-gnu/ruby/2.1.0/io/console.so
   39 /usr/lib/ruby/2.1.0/rubygems/user_interaction.rb
   40 /usr/lib/ruby/2.1.0/rubygems/config_file.rb
   41 /usr/lib/ruby/vendor_ruby/bundler/rubygems_integration.rb
   42 /usr/lib/ruby/vendor_ruby/bundler/version.rb
   43 /usr/lib/ruby/vendor_ruby/bundler/constants.rb
   44 /usr/lib/ruby/vendor_ruby/bundler/current_ruby.rb
   45 /usr/lib/ruby/vendor_ruby/bundler.rb
   46 /usr/lib/ruby/vendor_ruby/vagrant/version.rb
   47 /usr/lib/ruby/vendor_ruby/vagrant/util/tempfile.rb
   48 /usr/lib/ruby/vendor_ruby/bundler/ui.rb
   49 /usr/lib/ruby/vendor_ruby/bundler/ui/silent.rb
   50 /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb
   51 /home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/version.rb
   52 /usr/lib/ruby/2.1.0/ostruct.rb
   53 /home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/generic_object.rb
   54 /home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/common.rb
   55 /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/utf_16be.so
   56 /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/utf_16le.so
   57 /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/utf_32be.so
   58 /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/utf_32le.so
   59 /home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/ext/parser.so
   60 /home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/ext/generator.so

* Process memory map:

00400000-00401000 r-xp 00000000 08:03 10880031                           /usr/bin/ruby2.1
00600000-00601000 r--p 00000000 08:03 10880031                           /usr/bin/ruby2.1
00601000-00602000 rw-p 00001000 08:03 10880031                           /usr/bin/ruby2.1
01861000-0212d000 rw-p 00000000 00:00 0                                  [heap]
7f53902e0000-7f53902f6000 r-xp 00000000 08:03 10224898                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f53902f6000-7f53904f5000 ---p 00016000 08:03 10224898                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f53904f5000-7f53904f6000 rw-p 00015000 08:03 10224898                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f53904f6000-7f5390500000 r-xp 00000000 08:03 11358389                   /home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/ext/generator.so
7f5390500000-7f53906ff000 ---p 0000a000 08:03 11358389                   /home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/ext/generator.so
7f53906ff000-7f5390700000 r--p 00009000 08:03 11358389                   /home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/ext/generator.so
7f5390700000-7f5390701000 rw-p 0000a000 08:03 11358389                   /home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/ext/generator.so
7f5390701000-7f5390702000 r-xp 00000000 08:03 10895359                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/utf_32le.so
7f5390702000-7f5390901000 ---p 00001000 08:03 10895359                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/utf_32le.so
7f5390901000-7f5390902000 r--p 00000000 08:03 10895359                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/utf_32le.so
7f5390902000-7f5390903000 rw-p 00001000 08:03 10895359                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/utf_32le.so
7f5390903000-7f5390904000 r-xp 00000000 08:03 10925652                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/utf_32be.so
7f5390904000-7f5390b03000 ---p 00001000 08:03 10925652                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/utf_32be.so
7f5390b03000-7f5390b04000 r--p 00000000 08:03 10925652                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/utf_32be.so
7f5390b04000-7f5390b05000 rw-p 00001000 08:03 10925652                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/utf_32be.so
7f5390b05000-7f5390b06000 r-xp 00000000 08:03 10882558                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/utf_16le.so
7f5390b06000-7f5390d06000 ---p 00001000 08:03 10882558                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/utf_16le.so
7f5390d06000-7f5390d07000 r--p 00001000 08:03 10882558                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/utf_16le.so
7f5390d07000-7f5390d08000 rw-p 00002000 08:03 10882558                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/utf_16le.so
7f5390d08000-7f5390d09000 r-xp 00000000 08:03 10882557                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/utf_16be.so
7f5390d09000-7f5390f09000 ---p 00001000 08:03 10882557                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/utf_16be.so
7f5390f09000-7f5390f0a000 r--p 00001000 08:03 10882557                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/utf_16be.so
7f5390f0a000-7f5390f0b000 rw-p 00002000 08:03 10882557                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/utf_16be.so
7f5390f0b000-7f5390f12000 r-xp 00000000 08:03 10234043                   /lib/x86_64-linux-gnu/librt-2.21.so
7f5390f12000-7f5391111000 ---p 00007000 08:03 10234043                   /lib/x86_64-linux-gnu/librt-2.21.so
7f5391111000-7f5391112000 r--p 00006000 08:03 10234043                   /lib/x86_64-linux-gnu/librt-2.21.so
7f5391112000-7f5391113000 rw-p 00007000 08:03 10234043                   /lib/x86_64-linux-gnu/librt-2.21.so
7f5391113000-7f5391356000 r-xp 00000000 08:03 10393091                   /home/augustin/.rvm/rubies/ruby-1.9.3-p385/lib/libruby.so.1.9.1
7f5391356000-7f5391555000 ---p 00243000 08:03 10393091                   /home/augustin/.rvm/rubies/ruby-1.9.3-p385/lib/libruby.so.1.9.1
7f5391555000-7f539155a000 r--p 00242000 08:03 10393091                   /home/augustin/.rvm/rubies/ruby-1.9.3-p385/lib/libruby.so.1.9.1
7f539155a000-7f539155e000 rw-p 00247000 08:03 10393091                   /home/augustin/.rvm/rubies/ruby-1.9.3-p385/lib/libruby.so.1.9.1
7f539155e000-7f539157b000 rw-p 00000000 00:00 0 
7f539157b000-7f5391581000 r-xp 00000000 08:03 11358393                   /home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/ext/parser.so
7f5391581000-7f5391780000 ---p 00006000 08:03 11358393                   /home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/ext/parser.so
7f5391780000-7f5391781000 r--p 00005000 08:03 11358393                   /home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/ext/parser.so
7f5391781000-7f5391782000 rw-p 00006000 08:03 11358393                   /home/augustin/.rvm/gems/ruby-1.9.3-p385/gems/json-1.8.2/lib/json/ext/parser.so
7f5391782000-7f5391785000 r-xp 00000000 08:03 10925725                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/io/console.so
7f5391785000-7f5391984000 ---p 00003000 08:03 10925725                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/io/console.so
7f5391984000-7f5391985000 r--p 00002000 08:03 10925725                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/io/console.so
7f5391985000-7f5391986000 rw-p 00003000 08:03 10925725                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/io/console.so
7f5391986000-7f5391989000 r-xp 00000000 08:03 10925716                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/etc.so
7f5391989000-7f5391b88000 ---p 00003000 08:03 10925716                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/etc.so
7f5391b88000-7f5391b89000 r--p 00002000 08:03 10925716                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/etc.so
7f5391b89000-7f5391b8a000 rw-p 00003000 08:03 10925716                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/etc.so
7f5391b8a000-7f5391b90000 r-xp 00000000 08:03 10925730                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/pathname.so
7f5391b90000-7f5391d8f000 ---p 00006000 08:03 10925730                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/pathname.so
7f5391d8f000-7f5391d90000 r--p 00005000 08:03 10925730                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/pathname.so
7f5391d90000-7f5391d91000 rw-p 00006000 08:03 10925730                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/pathname.so
7f5391d91000-7f5391d94000 r-xp 00000000 08:03 10925717                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/thread.so
7f5391d94000-7f5391f93000 ---p 00003000 08:03 10925717                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/thread.so
7f5391f93000-7f5391f94000 r--p 00002000 08:03 10925717                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/thread.so
7f5391f94000-7f5391f95000 rw-p 00003000 08:03 10925717                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/thread.so
7f5391f95000-7f5391f97000 r-xp 00000000 08:03 10924576                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/trans/transdb.so
7f5391f97000-7f5392197000 ---p 00002000 08:03 10924576                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/trans/transdb.so
7f5392197000-7f5392198000 r--p 00002000 08:03 10924576                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/trans/transdb.so
7f5392198000-7f5392199000 rw-p 00003000 08:03 10924576                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/trans/transdb.so
7f5392199000-7f539219b000 r-xp 00000000 08:03 10888108                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/encdb.so
7f539219b000-7f539239a000 ---p 00002000 08:03 10888108                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/encdb.so
7f539239a000-7f539239b000 r--p 00001000 08:03 10888108                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/encdb.so
7f539239b000-7f539239c000 rw-p 00002000 08:03 10888108                   /usr/lib/x86_64-linux-gnu/ruby/2.1.0/enc/encdb.so
7f539239c000-7f539266a000 r--p 00000000 08:03 10879045                   /usr/lib/locale/locale-archive
7f539266a000-7f5392771000 r-xp 00000000 08:03 10234039                   /lib/x86_64-linux-gnu/libm-2.21.so
7f5392771000-7f5392970000 ---p 00107000 08:03 10234039                   /lib/x86_64-linux-gnu/libm-2.21.so
7f5392970000-7f5392971000 r--p 00106000 08:03 10234039                   /lib/x86_64-linux-gnu/libm-2.21.so
7f5392971000-7f5392972000 rw-p 00107000 08:03 10234039                   /lib/x86_64-linux-gnu/libm-2.21.so
7f5392972000-7f539297b000 r-xp 00000000 08:03 10234024                   /lib/x86_64-linux-gnu/libcrypt-2.21.so
7f539297b000-7f5392b7a000 ---p 00009000 08:03 10234024                   /lib/x86_64-linux-gnu/libcrypt-2.21.so
7f5392b7a000-7f5392b7b000 r--p 00008000 08:03 10234024                   /lib/x86_64-linux-gnu/libcrypt-2.21.so
7f5392b7b000-7f5392b7c000 rw-p 00009000 08:03 10234024                   /lib/x86_64-linux-gnu/libcrypt-2.21.so
7f5392b7c000-7f5392baa000 rw-p 00000000 00:00 0 
7f5392baa000-7f5392bad000 r-xp 00000000 08:03 10228737                   /lib/x86_64-linux-gnu/libdl-2.21.so
7f5392bad000-7f5392dac000 ---p 00003000 08:03 10228737                   /lib/x86_64-linux-gnu/libdl-2.21.so
7f5392dac000-7f5392dad000 r--p 00002000 08:03 10228737                   /lib/x86_64-linux-gnu/libdl-2.21.so
7f5392dad000-7f5392dae000 rw-p 00003000 08:03 10228737                   /lib/x86_64-linux-gnu/libdl-2.21.so
7f5392dae000-7f5392e2c000 r-xp 00000000 08:03 10888142                   /usr/lib/x86_64-linux-gnu/libgmp.so.10.2.0
7f5392e2c000-7f539302c000 ---p 0007e000 08:03 10888142                   /usr/lib/x86_64-linux-gnu/libgmp.so.10.2.0
7f539302c000-7f539302d000 r--p 0007e000 08:03 10888142                   /usr/lib/x86_64-linux-gnu/libgmp.so.10.2.0
7f539302d000-7f539302e000 rw-p 0007f000 08:03 10888142                   /usr/lib/x86_64-linux-gnu/libgmp.so.10.2.0
7f539302e000-7f5393046000 r-xp 00000000 08:03 10234022                   /lib/x86_64-linux-gnu/libpthread-2.21.so
7f5393046000-7f5393246000 ---p 00018000 08:03 10234022                   /lib/x86_64-linux-gnu/libpthread-2.21.so
7f5393246000-7f5393247000 r--p 00018000 08:03 10234022                   /lib/x86_64-linux-gnu/libpthread-2.21.so
7f5393247000-7f5393248000 rw-p 00019000 08:03 10234022                   /lib/x86_64-linux-gnu/libpthread-2.21.so
7f5393248000-7f539324c000 rw-p 00000000 00:00 0 
7f539324c000-7f539340c000 r-xp 00000000 08:03 10234049                   /lib/x86_64-linux-gnu/libc-2.21.so
7f539340c000-7f539360c000 ---p 001c0000 08:03 10234049                   /lib/x86_64-linux-gnu/libc-2.21.so
7f539360c000-7f5393610000 r--p 001c0000 08:03 10234049                   /lib/x86_64-linux-gnu/libc-2.21.so
7f5393610000-7f5393612000 rw-p 001c4000 08:03 10234049                   /lib/x86_64-linux-gnu/libc-2.21.so
7f5393612000-7f5393616000 rw-p 00000000 00:00 0 
7f5393616000-7f5393863000 r-xp 00000000 08:03 10879702                   /usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1.0
7f5393863000-7f5393a63000 ---p 0024d000 08:03 10879702                   /usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1.0
7f5393a63000-7f5393a69000 r--p 0024d000 08:03 10879702                   /usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1.0
7f5393a69000-7f5393a6d000 rw-p 00253000 08:03 10879702                   /usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1.0
7f5393a6d000-7f5393a91000 rw-p 00000000 00:00 0 
7f5393a91000-7f5393ab5000 r-xp 00000000 08:03 10234020                   /lib/x86_64-linux-gnu/ld-2.21.so
7f5393b7e000-7f5393c84000 rw-p 00000000 00:00 0 
7f5393cad000-7f5393cae000 rw-p 00000000 00:00 0 
7f5393cae000-7f5393caf000 ---p 00000000 00:00 0 
7f5393caf000-7f5393cb4000 rw-p 00000000 00:00 0                          [stack:23665]
7f5393cb4000-7f5393cb5000 r--p 00023000 08:03 10234020                   /lib/x86_64-linux-gnu/ld-2.21.so
7f5393cb5000-7f5393cb6000 rw-p 00024000 08:03 10234020                   /lib/x86_64-linux-gnu/ld-2.21.so
7f5393cb6000-7f5393cb7000 rw-p 00000000 00:00 0 
7ffdc991c000-7ffdc993e000 rw-p 00000000 00:00 0 
7ffdc99a2000-7ffdc99a4000 r--p 00000000 00:00 0                          [vvar]
7ffdc99a4000-7ffdc99a6000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]


[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

./configure.sh: line 87: 23663 Aborted                 (core dumped) GAIA_PATH=${PWD}/gaia vagrant up
```

**Comment by autra** [comment]
Closing. Removing bash entry for ruby and rvm fixed the issue. I don't know what's going on, but I won't miss it anyway :-)
